# production build
# http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html
FROM webdevops/php-nginx:7.1 as production

# set the document root
ENV WEB_DOCUMENT_ROOT /var/www/html/public

#RUN apt-get update \

# Install PostreSQL
RUN apt-get update \
  && apt-get install -y libpq-dev \
  && docker-php-ext-install pdo_pgsql

# expose doc root
VOLUME ["/var/www/html"]
